language: python

sudo: false

python:
        - "3.6"
install:
        - pip install -r requirements.txt
script:
        - coverage erase
        - coverage run test_add.py
before_install:
        - pip install codecov
after_sucess:
        - codecov -t $CODECOV_TOKEN
        - echo $CODECOV_TOKEN
