language: python
sudo: required 
python:
        - "3.6"
install:
        - pip install -r requirements.txt
script:
        - nosetests --with-coverage
before_install:
        - pip install --user codecov
after_sucess:
        - codecov --file coverage/lcov.info --diable search
