language: python
sudo: required 
python:
        - "2.7"
        - "3.5"
        - "3.6"
install:
        - pip install -r requirements.txt
script:
        - nosetests -v --with-coverage
after_sucess:
        - bash < (curl -s https://codecov.io/bash)
