language: python
sudo: required 
python:
        - "3.6"
install:
        - pip install -r requirements.txt
script:
        - nosetests --with-coverage
before_install:
        - pip install codecov
after_sucess:
        - bash <(curl -s https://codecov.io/bash)
