language: python

sudo: true

python:
        - "3.6"
install:
        - pip install -r requirements.txt
script:
        - coverage run test_add.py
before_install:
        - pip install --user codecov
after_sucess:
        - codecov -t $CODECOV_TOKEN
        - echo $CODECOV_TOKEN
